### ISSUE TITLE
Can't get it to work with SK6812 RGBW

### ISSUE THREAD

**Issue by dvmourik** [Grooviee/HomeyLedstrip#4]
Hello,

I installed McLighting V3 on a Wemos D1 Mini, Node MCU V1 and V2
Can't get it to work with my SK6812 ledstrip (5m). When i power it with my 100W power supply (90W needed for 5m) i only get like 75% of the LEDS to turn on but i can't get it working in colors. It's all random and not working like it should.

Can you guide me a bit in the direction to get the SK6812 working. I want to use them with Homey.

**Comment by Grooviee** [comment]
The random colors could be that the RGBW-order isn't set correctly in the McLightning settings. 

For the problem of not all the leds turning on: did you also set the correct number of leds in the McLighting-settings? 

You might also want to post your problem in https://github.com/FabLab-Luenen/McLighting, because I think this is more a McLighting-problem than a problem in the Homey-app I've made.

**Comment by dvmourik** [comment]
You're totally correct, i just solved it ... stupid me... i connected the led strip to 5V and the D1 to USB... the output voltage is 3.3V in that situation... not enough to sent a valid data line... now connected the D1 to 5V too and it works!

Keep up the great work!!!!

**Comment by Grooviee** [comment]
Nice to hear that you solved the problem. If you have any other questions/improvments just let me know.
